config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :drinks
  resources :venues do
    resources :drinks_opportunities
  end
  resources :drinks_opportunities, only: :show  do
    resources :bids
  end

  resources 'profile', to: 'users_profile#index' , as: :profile, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  # REFERENCES
  belongs_to :user
  belongs_to :drinks_opportunity
  # VALIDATIONS

  validates :contract, presence: true
  validates :price, presence: true
  validates :notes, presence: true
end

app/models/drink.rb
class Drink < ApplicationRecord
  validates :name, presence: true
end

app/models/drinks_opportunity.rb
class DrinksOpportunity < ApplicationRecord
  # REFERENCES
  has_one :drink
  belongs_to :venue
  has_many :bids
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :quantity, presence: true
  validates :bottle_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # REFERENCES
  has_many :venues
  has_many :drinks_opportunities
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # VALIDATIONS
end

app/models/venue.rb
class Venue < ApplicationRecord
    # MAPBOX
  geocoded_by :post_code
  after_validation :geocode, if: :will_save_change_to_post_code?
  # PG SEARCH

  include PgSearch::Model
  pg_search_scope :search,
  against: [ :venue_name, :city, :region ],
  using: {
    tsearch: { prefix: true }
    }

  # REFERENCES
  has_many :bids, through: :drinks_opportunity
  belongs_to :user
  has_many :drinks_opportunities
  # VALIDATIONS
  has_one_attached :photo
  validates :venue_name, presence: true
  validates :description, presence: true
  validates :region, presence: true
  validates :city, presence: true
  validates :post_code, presence: true
  #ACTION TEXT
  has_rich_text :info
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[index show home]
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def index
    @bids = Bid.all
  end

  def show
    @bid = Bid.find(params[:id])
  end

  def new
    @drink_opportunity = DrinksOpportunity.find(params[:drinks_opportunity_id])
    @bid = Bid.new
  end

  def create
    @drink_opportunity = DrinksOpportunity.find(params[:drinks_opportunity_id])
    @bid = Bid.new(bid_params)
    @bid.user_id = current_user.id
    @bid.drinks_opportunity_id = @drink_opportunity.id
    if @bid.save
      redirect_to venue_path(@drink_opportunity.venue.id), notice: "The bid was created with success."
    else
      raise
      render :new
    end
  end

  def edit
    @bid = Bid.find(params[:id])
  end

  def update
    @bid = Bid.find(params[:id])
    if @bid.update(bid_params)
      redirect_to bid_path(@bid)
    else
      render :edit
    end
  end

  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy
    redirect_to bid_path
  end

  private

  # PARAMS

  def bid_params
    params.require(:bid).permit(:contract, :price, :notes)
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  # CREATE
  def create
    @venue = Venue.find(params[:venue_id])
    @drink = Drink.new(drinks_params)
    @drink.venue = @drink
    @drink.save
  end

  # DESTROY
  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy
  end

  private

  def drinks_params
    params.require(:drinks).permit(:name)
  end
end

app/controllers/drinks_opportunities_controller.rb
class DrinksOpportunitiesController < ApplicationController
  # INDEX

  def index
    @drinks_opportunities = DrinksOpportunity.all
  end

  # SHOW

  def show
    @drinks_opportunities = DrinksOpportunity.find(params[:id])
  end

  # NEW

  def new
    @drink_opportunity = DrinksOpportunity.new
  end

  # EDIT

  def edit
     @drink_opportunity = DrinksOpportunity.find(params[:id])
  end

  # UPDATE

  def update
    @drink_opportunity = DrinksOpportunity.find(params[:id])
      if @drink_opportunity.update(drinks_opportunities_params)
        redirect_to drink_opportunity(@drink_opportunity)
      else
        render :edit
      end
   end

  # CREATE

  def create
    @drink_opportunity = DrinkOpportunity.new(drinks_opportunities_params)
    @drink_opportunity.user = current_user
    if @drink_opportunity.save
      redirect_to drink_opportunity(@drink_opportunity)
      else
        render :new
      end
   end

  # DESTROY

  def destroy
    @drink_opportunity = DrinkOpportunity.find(params[:id])
    @drink_opportunity.destroy
    redirect_to venues_path
  end

 private

  def drinks_opportunities_params
    params.require(:drink_opportunity).permit(:bid_id, :quantity, :start_time, :end_time, :drink_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @venues = Venue.all.sample(3)
  end
end

app/controllers/users_profile_controller.rb
class UsersProfileController < ApplicationController
  def index
    @venues = Venue.all
    @bids = Bid.all
    @drinksopportunities = DrinksOpportunity.all
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @query = params[:query]
    if not @query or @query.empty?
      @venues = Venue.all
      return
    end
    #@venues = Venue.search(params[:query])
    # @venues = Venue.select { |venue| venue.drinks_opportunities.drink_id.include?(Drink.find_by(name: params[:query])) }
    @drinks = Drink.where("name ILIKE ?", "%#{params[:query]}%")

    @venues = []

    Venue.all.each do |venue|
      venue.drinks_opportunities.each do |opportunity|
           @drinks.each do |drink|
            if opportunity.drink_id == drink.id
                @venues << venue
            end
          end
      end
    end

    if @venues.empty?
      @venues = Venue.all
    end
end

  def show
    @bid = Bid.new
    @venue = Venue.find(params[:id])
      @markers = [
        {
          lat: @venue.latitude,
          lng: @venue.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { venue: @venue })
        }
      ]
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to venue_path(@venue), notice: "The venue was created with success."
    else
      render :new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue = Venue.find(params[:id])
    if @venue.update(venue_params)
      redirect_to venue_path(@venue)
    else
      render :edit
    end
  end

  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy
    redirect_to venues_path
  end

  private

  # PARAMS

  def venue_params
    params.require(:venue).permit(:venue_name, :description, :region, :city, :post_code, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bids/destroy.html.erb
<h1>Bids#destroy</h1>
<p>Find me in app/views/bids/destroy.html.erb</p>

app/views/bids/edit.html.erb
<h1>Bids#edit</h1>
<p>Find me in app/views/bids/edit.html.erb</p>

app/views/bids/index.html.erb
<h1>Bids#index</h1>
<p>Find me in app/views/bids/index.html.erb</p>

app/views/bids/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@drink_opportunity, @bid] do |f| %>
        <%= f.input :contract, label:false %>
        <%= f.input :notes, placeholder: 'Insert the description of your offer here', label:false %>
        <%= f.input :price, placeholder: 'Insert your price in £', label:false %>
        <%= f.submit "Send your Bid" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bids/partial/_bid.html.erb
<!-- Button trigger modal -->
<a type="" class="btn btn-auction" data-toggle="modal" data-target="#exampleModal">
  Create bid
</a>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create bid</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@drink_opportunity = @opportunity, @bid] do |f| %>
        <%= f.label "contract"%>
        <%= f.input :contract, label:false %>
        <%= f.label "Notes"%>
        <%= f.input :notes, placeholder: 'Insert the description of your offer here', label:false %>
        <%= f.label "Price"%>
        <%= f.input :price, placeholder: 'Insert your price in £', label:false %>
        <%= f.submit "Send your Bid", class: "btn btn-auction" %>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/bids/show.html.erb
<h1>Bids#show</h1>
<p>Find me in app/views/bids/show.html.erb</p>

app/views/bids/update.html.erb
<h1>Bids#update</h1>
<p>Find me in app/views/bids/update.html.erb</p>

app/views/drinks_opportunities/index.html.erb
<% @drinks_opportunities.each do |drinksopportunity| %>
          <% if current_user.id === drinksopportunity.venue.user_id %>
            <tr class="row-border">
              <td> <%= drinksopportunity.venue.venue_name %> </td>
              <td> <%= drinksopportunity.start_time %> </td>
              <td> <%= link_to "" , edit_drinks_opportunity_path(drinksopportunity), class:"fas fa-pencil-alt", style:"margin-right:10px;"%> </td>
              <td> <%= link_to "" , drinks_opportunity_path(drinksopportunity), class:"far fa-trash-alt", method: :delete %></td>
            </tr>
          <% end %>
        <% end %>

app/views/drinks_opportunities/new.html.erb
<div class="container">
  <div class="row new-from-create justify-content-center">
    <div class="col-12 col-sm-12 form-login">
      <%= simple_form_for (@drink_opportunity) do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time  %>
        <%= f.input :quantity, label: false, placeholder: "Quantity" %>
        <%= f.input :bottle_type, label: false, placeholder: "Specify the type of container" %>
        <%= f.button :submit, class: 'btn btn-primary'  %>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eztenda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('beeer.png') %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

      <div class="page-container">
        <%= render "shared/navbar" %>
        <div class="content-container"><%= yield %></div>
        <div class="footer-container"><%= render "shared/footer" %></div>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

  <div class="container mt-4">
  <div class="row">
    <div class="col-12">
      <h1 style="font-weight: bold;" class="text-center featured-pub">Featured Pubs</h1>
    </div>
  </div>
  <div class="row">
    <% @venues.each do |venue| %>
      <div class="col-12 col-sm-6 col-md-4">
        <% if venue.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path venue.photo.key %>');">
            <h1><%= venue.venue_name %></h1>
          </div>
        <% else %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://www.historic-uk.com/wp-content/uploads/2019/02/oldest-pub-in-england-2800x1440.jpg');">
            <h1><%= venue.venue_name %></h1>
          </div>
        <% end %>

          <div class="card-product box-shadow mb-4">
            <h2><%= venue.venue_name %></h2>
            <p><i class="fas fa-map-marker-alt"></i> <%= venue.city %>, <%= venue.post_code %></p>
              <div class="d-flex mt-2">
                <% venue.drinks_opportunities.each do |opportunity| %>
                  <div class="tag"> <%= Drink.find(opportunity.drink_id).name %></div>
                <% end %>
              </div>
              <div class="d-flex mt-4">
            <%= link_to "Join Auction", venue_path(venue.id), class: "btn-auction" %>
          </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-12 home-works">
          <h1 style="font-weight: bold;" class="text-center mt-2 mb-3">How It Works</h1>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-xs-12 col-md-4 text-center">
        <i class="fas fa-search-dollar fa-3x"></i>
        <h3 class="my-3">Search</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      </div>

      <div class="col-xs-12 col-md-4 text-center">
        <i class="fas fa-beer fa-3x"></i>
        <h3 class="my-3">Bid</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      </div>

       <div class="col-xs-12 col-md-4 text-center">
        <i class="fab fa-amazon-pay fa-3x"></i>
        <h3 class="text-center my-3">Accept</h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
      </div>
    </div>
   </div>
</div>

app/views/shared/_banner.html.erb
<!-- <div class="banner">
  <div class="text-left">
    <h1>Tendering made easy</h1>
    <p>Save your time by using our app..</p>
  </div>
</div> -->

<div class="jumbotron">
  <div class="container d-flex">
    <div class="col-md-6">
      <h1 class="display-4">A better way for bars and brands to do business</h1>
      <p>The online auction where bars can tender their listings deals and drinks brands can bid for them.</p>
      <a class="btn btn-gray btn-lg" href="#" role="button">Get started</a>
      <a class="btn btn-white btn-lg" href="#" role="button">Watch demo</a>
  </div>
    <div class="col-md-6" id="banner-img">
      <%= image_tag "banner-img.png", class: "banner-img" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

<div class="container">
  <div class="footer-copyright">
      <p><%= "🍺" %> <strong>Eztenda</strong> 2021</p>
    </div>
    <div class="footer-links">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-spotify"></i></a>
    </div>
</div>

</div>

app/views/shared/_navbar.html.erb
<div class="nav-wrapper">
  <div class="container">
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
          <%= link_to "/venues", class: "navbar-brand" do %>
            <%= image_tag "logo.png" %>
            <% end %>


  <div class="row">
    <div class="col-12">
      <%= form_tag venues_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "🔍 Search for tenders"
      %>
    </div>
  <% end %>
  </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item active mr-4">
                  <%= link_to "HOW IT WORKS", "#", class: "nav-link", id: "nav-tab" %>
                </li>
                <li class="nav-item active mr-4">
                  <%= link_to "USE CASES", "#", class: "nav-link", id: "nav-tab" %>
                </li>
                <li class="nav-item active mr-4">
                  <%= link_to "ABOUT US", "#", class: "nav-link", id: "nav-tab" %>
                </li>
                <li class="nav-item dropdown">
                  <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
                  <% else %>
                    <%= image_tag "https://icon-library.com/images/no-profile-pic-icon/no-profile-pic-icon-12.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <%= link_to "Account", profile_index_path(current_user), class: "dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "LOG IN", new_user_session_path, class: "nav-link mr-3" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign up", new_user_registration_path, class: "nav-link sign-up-button btn btn-gray btn-sm p-2 border-gray" %>
                </li>
              <% end %>
            </ul>
      </div>
    </div>
  </div>
</div>

 <div class="flex-row filter-tabs-row d-none">
      <ul class="navbar-nav flex-row", id="filter-tabs">
        <li class="nav-item active mr-2">
          <%= link_to "Lager", "venues?query=lager", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Cider", "venues?query=cider", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Craft beer", "venues?query=craft beer", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Bitter", "venues?query=bitter", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Stout", "venues?query=stout", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Red wine", "venues?query=red wine", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "White wine", "venues?query=white wine", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Sparkling wine", "venues?query=sparkling wine", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Fortified wine", "venues?query=fortified wine", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Champagne", "venues?query=champagne", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "Carbonated soft drinks", "venues?query=carbonated soft drinks", class: "nav-link", id: "nav-tab" %>
        </li>
        <li class="nav-item active mr-4">
          <%= link_to "See all categories", "/venues", class: "nav-link", id: "nav-tab" %>
        </li>
      </ul>
    </div>

app/views/users_profile/_profile_account.html.erb
<div class="row p-5">
  <div class="table-responsive">
  <table class="table">
    <tbody>
         <tr class="row-border">
          <td class="label"><strong>First Name:</strong></td>
          <td class="label"><strong>Last Name:</strong></td>
          <td class="label"><strong>E-mail:</strong></td>
        </tr>
         <tr class="row-border">
              <td><%= current_user.first_name %></td>
              <td><%= current_user.last_name %></td>
              <td> <%= current_user.email%></td>
            </tr>
    </tbody>
  </table>

      <div class="col-md-4">
      <%= link_to "Create Venue", new_venue_path, class: "btn btn-auction" %>
    </div>

</div>
</div>

app/views/users_profile/_profile_bids.html.erb
<div class="row p-5">
  <div class="table-responsive">
    <table class="table">

      <tbody>
        <tr class="row-border">
          <td class="label">Venue name</td>
          <td class="label">Situation</td>
           <td class="label">Price:</td>
           <td class="label">Drink:</td>
           <td class="label">Contract:</td>
        </tr>

        <% @bids.each do |bid| %>

         <% if current_user.id === bid.user_id %>
            <tr class="row-border">
              <% venue = DrinksOpportunity.find(bid.drinks_opportunity_id).venue %>
              <td> <%= link_to venue.venue_name, venue_path(venue)%></td>
              <% if bid.is_accepted %>
                <td> Accepted </td>
              <% else %>
                <td> Not accepeted </td>
              <% end %>
              <td> <%= bid.price %> </td>
              <% drink = DrinksOpportunity.find(bid.drinks_opportunity_id).drink_id%>
              <td> <%= Drink.find(drink).name%> </td>
              <td> <%= bid.notes%> </td>
            </tr>
           <% end %>
         <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/venues/_info_window.html.erb
<h2><%= @venue.venue_name %></h2>
<p><%= @venue.post_code %></p>

app/views/venues/create.html.erb
<h1>Venues#create</h1>
<p>Find me in app/views/venues/create.html.erb</p>

app/views/venues/show.html.erb
<div class ="container">
  <div class="row d-flex mt-5">
    <div class="col-md-8">
      <div class="row d-flex">
        <div class="col-md-12">
        <% if @venue.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @venue.photo.key %>');">
            <h1><%= @venue.venue_name %></h1>
          </div>
        <% else %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://www.historic-uk.com/wp-content/uploads/2019/02/oldest-pub-in-england-2800x1440.jpg');">
            <h1><%= @venue.venue_name %></h1>
          </div>
        <% end %>
        </div>
      </div>

        <div class="container">
          <div class="row d-flex">
            <% if @venue.user == current_user %>
              <div class="mr-2"><%= link_to 'List your Drink', new_drinks_opportunity_path(@drink_opportunity), class: 'mt-4  btn btn-success'%></div>
              <div class="mr-2"><%= link_to "Edit venue", edit_venue_path(@venue), class: 'mt-4  btn btn-warning'%></div>
              <div> <%= link_to "Delete venue", venue_path(@venue), class: 'mt-4  btn btn-secondary', method: :delete, data: { confirm: 'Are you sure that you want to delete this venue?' } %></div>
            <% end %>
          </div>
        </div>


        <div class="card p-3 mt-3">
          <p><%= @venue.description %></p>
        </div>

          <% @venue.drinks_opportunities.each do |opportunity|  %>
          <% @opportunity = opportunity %>
          <div class="card mt-3 p-3">
            <h4 class="border-bottom"><strong>Listing Opportunity #:</strong> <%=opportunity.id %></h4>
            <p class="mt-3"><strong>Drink type:</strong> <%= Drink.find(opportunity.drink_id).name %></p>
            <p><strong>Estimated qty:</strong> <%=opportunity.quantity %> <%=opportunity.bottle_type %></p>
            <p><strong>Listing dates:</strong> <%=opportunity.start_time.strftime('%e %B %Y') %> - <%=opportunity.end_time.strftime('%e %B %Y') %> </p>

            <h4 class="mt-2"><strong>Current bids</strong></h4>
            <% if opportunity.bids.any? %>

            <table>
                <tr class="row-border">
                  <th class="lable-sm"> Name: </th>
                  <th class="lable-sm">Price: </th>
                  <th class="lable-sm">Date: </th>
                </tr>
              <% opportunity.bids.each do |bid| %>
                <tr class="row-border">
                  <td><%= bid.user.first_name%> <%=bid.user.last_name %></td>
                  <td>£<%= bid.price %></td>
                  <td><%= bid.created_at.strftime('%e %B %Y') %></td>
                </tr>
              <% end %>
            </table>


            <% else %>
              <p>No open bids</p>
            <%#= link_to "Place bid", new_drinks_opportunity_bid_path(opportunity), class: "btn-auction mt-3" %>
             <% end %>
          </div>
          <%= render "bids/partial/bid" %>
          <% end %>
    </div>

    <div class="col-md-4">
      <div class="card col-md-12 p-3">
          <div id="map"
           style="width: 100%; height: 600px;"
           data-markers="<%= @markers.to_json %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
          <p class="mt-3"><strong>Region:</strong><%= @venue.region %></p>
          <p><strong>City:</strong><%= @venue.city %></p>
          <p><strong>Post Code:</strong><%= @venue.post_code %></p>
      </div>
    </div>
  </div>
</div>